### PR TITLE
PCBs

### PR DESCRIPTION
**Pull request by Mobius5150**
This PR contains the PCBs that were ordered 2/8/2016.

### CODE REVIEW

**Comment by jbcuglietta** [comment]
During the discussion the power off was to be replaced by a NAND gate. Typo?

**Comment by Mobius5150** [comment]
@jbcuglietta No he misunderstood the schematic and I didn't catch it in the meeting. A NOR gate is correct.

**Comment by Mobius5150** [comment]
The input to SYSOFF is the logical negation of `JACKPWR + MCUPWR`

**Comment by jbcuglietta** [comment]
What does sysoff do again

**Comment by Mobius5150** [comment]
That's the pin that disconnects the battery when asserted HIGH

**Pull request merged**
